# This file was generated by GoReleaser. DO NOT EDIT.
cask "powerctl" do
  version "0.4.2"

  on_macos do
    on_arm do
      sha256 "33e1661c79341542a8960c7dd64599a0764682c62923617eee3acad4a25d4c61"
      url "https://github.com/kristofferrisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "68fedafa5af30054bc185be8d1d339f49996f6f67107fc14d93513556762228f"
      url "https://github.com/kristofferrisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a8c45dcbe52ee155ac1cbb27f380040d26ae1f3e2818fec706eb82f14afb9130"
      url "https://github.com/kristofferrisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c78c61c442d5a0189e67472034ad5bc842546bdce17aaa0809a6ab70e31324ed"
      url "https://github.com/kristofferrisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "powerctl"
  desc "CLI tool for monitoring electricity consumption and tracking power costs via Tibber"
  homepage "https://github.com/KristofferRisa/powerctl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "powerctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/powerctl"]
    end
  end

  # No zap stanza required
end
