# This file was generated by GoReleaser. DO NOT EDIT.
cask "powerctl" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "9317e7aa34326ee9e0aace80d9b8eb153a8a5b3d2916744b17b72267121ce913"
      url "https://github.com/KristofferRisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "76670bf83a170bdb3ba94f7e48f15eed7f1cc45166334dfcc649f4ae13b56070"
      url "https://github.com/KristofferRisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "8ca18bcb80783426524b213ac394f9ce7c855f1611805d87288bac9f135a0a0e"
      url "https://github.com/KristofferRisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be17f2aa4e2bca71b809c2f1feb10a291828b2e0bf4a9630813f2bbb6fd31902"
      url "https://github.com/KristofferRisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "powerctl"
  desc "CLI tool for monitoring electricity consumption and tracking power costs via Tibber"
  homepage "https://github.com/KristofferRisa/powerctl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "powerctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/powerctl"]
    end
  end
end
