# This file was generated by GoReleaser. DO NOT EDIT.
cask "powerctl" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "9bf7e20a6e0ae214d261d24d746e8cdbb5fc9706eb1669a35e4d8abe3ab60cf3"
      url "https://github.com/kristofferrisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1dcc67e20402c763b74a30c42e6e6249b80a73baea5dac9962f119c8ac196a7"
      url "https://github.com/kristofferrisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8d07f58ec05e2b1c5e88cbf6b08618e945bc141cc697bde61b96941de98d8145"
      url "https://github.com/kristofferrisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a5ff37cac9c2bc1ef5b1764b12e36e8ca09c4d9130da9762cccad284e85c3d2"
      url "https://github.com/kristofferrisa/powerctl-cli/releases/download/v#{version}/powerctl-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "powerctl"
  desc "CLI tool for monitoring electricity consumption and tracking power costs via Tibber"
  homepage "https://github.com/KristofferRisa/powerctl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "powerctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/powerctl"]
    end
  end

  # No zap stanza required
end
